### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by suryaavala** [Chybby/Tutorifull#2]
Great Job! It is a handy little tool.
Is this site (https://tutorifull.chybby.com/) still working and updated to get 18s1 enrollments? 
I have tried setting up a reminder for COMP9417, but the course doesn't show up in the search. 
Only two COMP9 courses are being displayed. 
![image](https://user-images.githubusercontent.com/15040594/31604169-350d8a7a-b2ae-11e7-91d2-64e4c915c39c.png)

**Comment by Chybby** [comment]
Switched over to sem 1.
Should work on getting it to switch automagically

**Comment by suryaavala** [comment]
Thanks dude! :)
